### ISSUE TITLE
Abuse report emails for CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by dlin303** [meetup/meetup-oss#2]
Currently the Contributors Covenant (CODE_OF_CONDUCT.md) for this project lists daron@meetup.com as the point of contact for reporting conduct violations. We should decide whether abuse reports should to individual(s) or to the organization (i.e. conductabuse@meetup.com) and make the necessary changes.

**Comment by chenrui333** [comment]
Should be good now. Closing the issue.
